#!/bin/bash
script_base_folder=$(dirname "$0")
source "${script_base_folder}/onedrive.cfg"
source "${script_base_folder}/onedrive-base"

echo "Please open the following URL in your browser and follow the steps until you see a blank page:"
echo "https://login.live.com/oauth20_authorize.srf?client_id=${api_client_id}&scope=wl.skydrive%20wl.skydrive_update%20wl.offline_access&response_type=code&redirect_uri=https://login.live.com/oauth20_desktop.srf"
echo ""
echo "When ready, please enter the value of the code parameter (from the URL of the blank page) and press return"
read code
api_json_result=$(curl -s -d "client_id=${api_client_id}&client_secret=${api_client_secret}&code=${code}&grant_type=authorization_code&redirect_uri=https://login.live.com/oauth20_desktop.srf" -X POST "${api_auth_url}")

refresh_token=$(extractJSONValue "${api_json_result}" "refresh_token")
if [ "${refresh_token}" != "" ]; then
    saveRefreshToken "${refresh_token}"
    echo "It seems like we have a refresh token, so we are ready to go"
else
    echo "Something went wrong, here is the API response:"
    echo "${api_json_result}"
fi
