#!/bin/bash

export script_base_folder=$(dirname "$0")
export script_base_name=$(basename "$0")

source "${script_base_folder}/onedrive.cfg"
source "${script_base_folder}/onedrive-base"

export json_parser="${script_base_folder}/libs/json/bash-json-parser"
export debug_mode=0

while [[ $# -ge 1 ]]; do
    case $1 in
        -h|--help)
            echo "Usage: ${script_base_name} [OPTIONS] file1 [file2...]"
            echo ""
            echo "Options:"
            echo "  -h, --help    Show this help"
            echo "  -f, --folder  Upload files into this remote folder"
            echo "                Directory names are separated with a slash, e.g."
            echo "                rootFolder/subFolder"
            echo "                Do NOT use a trailing slash!"
            exit 0
            ;;
        -f|--folder)
            shift
            folder_name="$1"
            shift
            ;;
        -d|--debug)
            shift
            debug_mode=1
            ;;
        *)
            break;
            ;;
    esac
done

if [ -z "$1" ]; then
        echo "Please specify at least one file to upload"
        exit 1
fi

if [ -n "${folder_name}" ]; then
	# TODO Throw an error, if $2 contains illegal characters like double quotes
    IFS='/' read -a folder_array <<< "${folder_name}"
    api_folder_id=$(getOrCreateFolder "${folder_array[@]}")
	exit_on_error
	
	export api_folder_id
    debug "api_folder_id is now '${api_folder_id}'"
fi

printf "%s\0" "${@}" | xargs -0 --max-procs=${max_upload_threads} -i'{}' bash -c "uploadFile \"{}\""
